// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buimypvgsqsrcasozqfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1aW15cHZnc3FzcmNhc296cWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDkwNzMsImV4cCI6MjA2MzU4NTA3M30.Y6aWURPGmR2sZVkqlOk-_HJQp2-dGiQikVPhnYvfyBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);